name: vllm-test

on:
  push:
    tags:
      - ciflow/vllm/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  get-label-type:
    name: get-label-type
    uses: pytorch/pytorch/.github/workflows/_runner-determinator.yml@main
    if: ${{ (github.event_name != 'schedule' || github.repository == 'pytorch/pytorch') && github.repository_owner == 'pytorch' }}
    with:
      triggering_actor: ${{ github.triggering_actor }}
      issue_owner: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}
      curr_branch: ${{ github.head_ref || github.ref_name }}
      curr_ref_type: ${{ github.ref_type }}
      opt_out_experiments: lf

  torch-build-sm89:
    name: cuda12.8-py3.12-gcc11-sm89-vllm-test
    uses: ./.github/workflows/_linux-build.yml
    needs: get-label-type
    with:
      build-additional-packages: "vision audio torchao"
      build-environment: linux-jammy-cuda12.8-py3.12-gcc11-sm89
      docker-image-name: ci-image:pytorch-linux-jammy-cuda12.8-cudnn9-py3.12-gcc11-vllm
      cuda-arch-list: '8.9'
      test-matrix: |
        { include: [
          { config: "vllm_basic_correctness_test", shard: 1, num_shards: 1, runner: "${{ needs.get-label-type.outputs.label-type }}linux.g6.4xlarge.experimental.nvidia.gpu"  },
          { config: "vllm_regression_test", shard: 1, num_shards: 1, runner: "${{ needs.get-label-type.outputs.label-type }}linux.g6.4xlarge.experimental.nvidia.gpu" },
          { config: "vllm_entrypoints_test_llm", shard: 1, num_shards: 1, runner: "${{ needs.get-label-type.outputs.label-type }}linux.g6.4xlarge.experimental.nvidia.gpu" },
          { config: "vllm_basic_models_test", shard: 1, num_shards: 1, runner: "${{ needs.get-label-type.outputs.label-type }}linux.g6.4xlarge.experimental.nvidia.gpu" },
        ]}
    secrets: inherit

  vllm-build-sm89:
    name: cuda12.8-py3.12-gcc11-sm89-vllm-test
    uses: ./.github/workflows/_linux-external-build-main.yml
    needs: [
      get-label-type,
      torch-build-sm89
    ]
    with:
      build-additional-packages: "vision audio"
      build-environment: linux-jammy-cuda12.8-py3.12-gcc11-sm89
      build-target: vllm
      ci-config: ".github/ci_configs/vllm.yaml"
      runner_prefix: ${{ needs.get-label-type.outputs.label-type }}
      docker-image: ${{ needs.torch-build-sm89.outputs.docker-image }}
      runner: linux.24xlarge.memory
    secrets: inherit

  vllm-test-sm89:
    name: cuda12.8-py3.12-gcc11-sm89-vllm-test
    uses: ./.github/workflows/_linux-test.yml
    needs: [
      linux-jammy-cuda12_8-cudnn9-py3_12-gcc11-vllm-build-89,
      linux-jammy-cuda12_8-cudnn9-py3_12-gcc11-vllm-external-build-sm89
    ]
    with:
      build-environment: linux-jammy-cuda12.8-py3.12-gcc11-sm89
      docker-image: ${{ needstorch-build-sm89.outputs.docker-image }}
      test-matrix: ${{ needs.torch-build-sm89.outputs.test-matrix }}
      additional-artifact-name: linux-jammy-cuda12.8-py3.12-gcc11-sm89-additional-build
    secrets: inherit
